### PR TITLE
Upgrade react and react-dom to 18

### PR DESCRIPTION
**Pull request by kevcenteno**

### CODE REVIEW

**Comment by mm-jpoole** [comment]
@kevcenteno 
I have a question, just to improve my understanding: I see you wrapped some things with fragments `<>`. Was that required due to the upgrade to 18, or something can't handle multiple children?

**Review by mm-jpoole — APPROVED** [review]
:+1:

**Comment by kevcenteno** [comment]
@mm-jpoole 

It's a typescript special.  When using conditionals like `someValue && <div>foobar</div>`, `someValue` has an `unknown` type which make typescript complain.

I suppose instead of wrapping with fragments, I could've double-banged `someValue` to make it into a `boolean`.  It should be easy to change.  Do you have a preference?

**Comment by mm-jpoole** [comment]
@kevcenteno Certainly no preference. My react is weak, especially with TS, so I just wanted to understand :smile:
I didn't even know what fragments were until 30 minutes ago, although I have run into some of the problems they solve with other frameworks like vue.

**Comment by kevcenteno** [comment]
Ah no worries.  I just wonder which one is more readable...

**Comment by mm-jpoole** [comment]
I think it's good as-is, makes sense to me

**Pull request merged**
