### PR TITLE
Update database size metrics

### PR DESCRIPTION
**Pull request by christophermluna**

### CODE REVIEW

**Review by dlieou — COMMENTED** [review]
Everything looks great.
Wondering how was each database size obtained?
Also, when I clicked on the preview link, and I wasn't able to get to see the relevant page(s). I looked around.

**Comment by christophermluna** [comment]
> Wondering how was each database size obtained?

there's a story in the Engineering PT called `Make it easier to update database size metrics on the Developer Portal` which documents the approach if you want to take a look.

> Also, when I clicked on the preview link, and I wasn't able to get to see the relevant page(s). I looked around.

e.g., https://a19611ce.dev-site-4ua.pages.dev/geoip/docs/databases/city-and-country/#database-sizes

let me know when it's approved so i can merge. thanks for the review!

**Comment by dlieou** [comment]
> > Wondering how was each database size obtained?
> 
> there's a story in the Engineering PT called `Make it easier to update database size metrics on the Developer Portal` which documents the approach if you want to take a look.
OK, that is fine. I was curious where these numbers come from. 
> 
> > Also, when I clicked on the preview link, and I wasn't able to get to see the relevant page(s). I looked around.
> 
> e.g., https://a19611ce.dev-site-4ua.pages.dev/geoip/docs/databases/city-and-country/#database-sizes
I see what is going on with the preview URLs, they were missing subsequent info. 
When clicked on it, it took me to the screenshot attached. 

I clicked on either one previously, and then View docs -> Database Documentation -> City and Country 
and didn't scroll down far enough to see the heading Database Sizes.
 
Screenshot 2024-10-22 at 8 19 14 AM

> 
> let me know when it's approved so i can merge. thanks for the review!

**Review by dlieou — APPROVED** [review]
Looks good. Thank you for the clarifications.

**Pull request merged**
