### PR TITLE
add copy for Snowflake team approval

### PR DESCRIPTION
**Pull request by AndraMeer**

### CODE REVIEW

**Comment by kevcenteno** [comment]
Hey @AndraMeer, the new dev site has been merged in, which means you'll want to close the PR and create a new one which edits this file instead (not the new `.md` file extension): https://github.com/maxmind/dev-site/blob/main/content/geoip/geolite2-free-geolocation-data.md

**Comment by AndraMeer** [comment]
hi @kevcenteno thank you, we need this to show the Snowflake team what/where the copy will be, so is it okay to leave this as a draft for now? Once we get approval, I will switch to the new one, thanks for letting me know!

**Comment by oschwald** [comment]
If they need to see the generated site, that may stop working early next week for the old blog.

**Comment by AndraMeer** [comment]
oh okay thank you for the heads-up, I will close this and create a new one then as we don't know how soon they will be able to review/approve. Much appreciated!

**Comment by AndraMeer** [comment]
Closing per above discussion.

**Pull request closed without merging**
