### PR TITLE
Improve Linting

### PR DESCRIPTION
**Pull request by wesrice**
This PR
- Removes the Write Good markdown integration. It was too noisy.
- Integrates Remark Linter in Gatsby's Webpack, allowing us to have feedback on markdown as we use `gatsby develop`.
- Adds Prettier formatting integration for mdx files only.
- Adds Yarn scripts to apply fixes from Remark Lint, Stylelint, ESLint
- Ensures out `lint-staged` git hooks attempt to fix files before committing them.
- Disables autofixing of Stylelint targets during `gatsby develop`

### CODE REVIEW

**Review by kevcenteno — COMMENTED** [review]
Looks good.  One consideration: I think it'd be a good idea to have eslint and prettier play nice together via https://prettier.io/docs/en/integrating-with-linters.html

**Comment by wesrice** [comment]
I tried to integrate Remark linting via Eslint, but Eslint tries to evaluate the MDX `<CodeSet>` elements, and the contents of those components are technically invalid JSX.

Currently, Prettier is only used for the Markdown files. So for now, I don't want to integrate it with ESLint just yet to avoid having to address the MDX parsing issue mentioned above.

**Comment by kevcenteno** [comment]
Ah I see... so what are we getting out of prettier that we can't get out of remark?

**Comment by wesrice** [comment]
Mainly, line-length fixing of prose longer than 80 characters, but avoiding line-length fixing for code blocks and tables.

**Pull request merged**
